package com.example.tracking_corona

const val BASE_URL = "https://disease.sh/v2/"
const val countriesReportUrl = "https://coronavirus-19-api.herokuapp.com/"
const val GUIDE_STUDENT_1_URL = "https://ncovi.vnpt.vn/views/huongdan_1.html"
const val GUIDE_STUDENT_2_URL = "https://ncovi.vnpt.vn/views/huongdan_2.html"
const val GUIDE_SCHOOL_1_URL = "https://ncovi.vnpt.vn/views/huongdan_8.html"
const val GUIDE_SCHOOL_2_URL = "https://ncovi.vnpt.vn/views/huongdan_9.html"
const val GUIDE_TRAVEL_URL = "https://ncovi.vnpt.vn/views/huongdan_3.html"
const val GUIDE_APARTMENT_1_URL = "https://ncovi.vnpt.vn/views/huongdan_4.html"
const val GUIDE_APARTMENT_2_URL = "https://ncovi.vnpt.vn/views/huongdan_5.html"
const val GUIDE_APARTMENT_3_URL = "https://ncovi.vnpt.vn/views/huongdan_6.html"
const val GUIDE_APARTMENT_4_URL = "https://ncovi.vnpt.vn/views/huongdan_14.html"
const val GUIDE_SUSPECT_URL = "https://ncovi.vnpt.vn/views/huongdan_7.html"
const val GUIDE_WORKSPACE_1_URL = "https://ncovi.vnpt.vn/views/huongdan_10.html"
const val GUIDE_WORKSPACE_2_URL = "https://ncovi.vnpt.vn/views/huongdan_17.html"
const val GUIDE_WORKSPACE_3_URL = "https://ncovi.vnpt.vn/views/huongdan_11.html"
const val GUIDE_WORKSPACE_4_URL = "https://ncovi.vnpt.vn/views/huongdan_12.html"
const val GUIDE_FAMILY_1_URL = "https://ncovi.vnpt.vn/views/huongdan_13.html"
const val GUIDE_FAMILY_2_URL = "https://ncovi.vnpt.vn/views/huongdan_15.html"
const val GUIDE_SERVICE_URL = "https://ncovi.vnpt.vn/views/huongdan_16.html"